name: db-funky_pixels
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - libffi=3.4.2
  - libsqlite=3.43.0
  - libzlib=1.2.13
  - openssl=3.1.2
  - pip=23.2.1
  - python=3.10.12
  - setuptools=68.1.2
  - tk=8.6.12
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wheel=0.41.2
  - xz=5.2.6
  - pip:
      - -r requirements.txt
